stages:
  - test

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

cache:
  paths:
  - vendor/

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/config/parameters.yml.dist app/config/parameters_test.yml
  - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters_test.yml"
  - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters_test.yml"
  - "echo '    redis_host: redis:6379' >> app/config/parameters_test.yml"
  - "echo '    redis_timeout: 1' >> app/config/parameters_test.yml"
  - "echo '    redis_reserved: null' >> app/config/parameters_test.yml"
  - "echo '    redis_retry_interval: 100' >> app/config/parameters_test.yml"
  - mkdir web/files
  - mkdir -p app/data/private_files
  - touch app/config/routing_plugins.yml

Unit Test With PHP 5.3:
  stage: test
  image: codeages/ci-php:5.3-2
  services:
    - mysql:5.5
    - redis:latest
  script:
    - phpunit -c app/
  only:
    - tags
    - develop
    - master
    - trigger

Unit Test With PHP 5.5:
  stage: test
  image: codeages/ci-php:5.5-5
  services:
    - mysql:5.5
    - redis:latest
  script:
    - php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection  `git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD`
    - phpunit -c app/

Unit Test With PHP 7.0:
  stage: test
  image: codeages/ci-php:7.0-7
  services:
    - mysql:5.5
    - redis:latest
  script:
    - sed -i 's/memory_limit.*/memory_limit = 2048M/g' /etc/php/7.0/phpdbg/php.ini
    - cat /etc/php/7.0/phpdbg/php.ini | grep memory_limit
    - phpdbg -qrr /usr/bin/phpunit -c app/ --coverage-text --colors=never
  only:
    - tags
    - develop
    - master
    - trigger

#Functional Test With 5.5:
#  stage: test
#  image: codeages/ci-php:5.5-5
#  services:
#    - mysql:5.5
#    - redis:latest
#    - selenium/standalone-chrome:latest
#  script:
#    - php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection  `git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD`
#    - SELENIUM_SERVER_URL="http://selenium__standalone-chrome:4444/wd/hub" phpunit -c tests/Functional
#  only:
#      - tags
#      - develop
#      - master
#      - trigger

Api Test With 5.5:
  stage: test
  image: ruanwenqin/ci-php:5.5-6
  services:
    - mysql:5.5
    - redis:latest
  script:
    - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters.yml"
    - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters.yml"
    - php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar config repo.packagist composer https://packagist.phpcomposer.com
    - php composer.phar require "codeception/codeception:*" --ignore-platform-reqs
    - app/console server:start
    - bin/codecept run api --debug